INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('진한 사골곰탕 300g', '100% 사골로 고은 진한 사골곰탕', 1750, 9, '실온', 0, 'img1')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('아워홈 포차 꼬치어묵 (시원한맛)', '국산 꽃게육수를 시원하게 담은 어묵탕', 5580, 30, '냉동', 0, 'img2')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('얼큰한 육개장 300g', '직접 솥에서 볶아 더 얼큰하고 맛있는', 3150, 5, '실온', 0, 'img3')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('뼈없는 갈비탕 400g', '뼈를 발라내어 먹기 편한 뼈없는 갈비탕', 6600, 10, '실온', 0, 'img4')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('아워홈 치킨스테이크 오리지널 920g (4인분)', '겉바속촉 통닭다리살 오븐구이 치킨스테이크', 17900, 5, '냉동', 1, 'img5')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('아워홈 들기름김 전장 20g (4gX5매)', '전장김, 들기름, 반찬, 간식', 2400, 5, '실온', 0, 'img6')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('소고기장조림 200g', '장조림, 간편반찬, 꽈리고추, 곤약', 3670, 0, '냉장', 0, 'img7')
INSERT INTO ITEM (product_name, description, price, dc, product_type, best_item, image) VALUES ('매콤한 칠리 닭가슴살 110g (냉장)', '단백질 함량 27g, 매콤한 칠리맛', 2980, 6, '냉장', 0, 'img8')
